# https://rosalind.info/problems/revc/
# Complementing a Strand of DNA exercise from ROSALIND

DNA = "TATTTCTCGCAGTTTAATTTCCCGCAGATAAAAGAGCTTCTTGTAAGACATGAATATCGACCTTTAATGGCATTCCTGGGCAAGTCTGCTCGATCCCCCACCCTGATCCCTCGTCCTGCTGGTATTGCTGCGGTGTACCCTACTGAACGTAATATCGGTCGGGTGGCACCATTTCCTCGGCAGAATCGGAATGCCCGTTCCAACATTTAACCTTCCACGCACAAGGGCGATAGCTACAGCACTTCTCTCCGCAAAGACTAGAAGATAAGCCAGCACCCCTACGATAGTTCCTAATGTCCCTAAACACATTGATAATTGAACCCTTGACCGTGTTTGCAGCCAACTCGTCAGGCATTACGTAAATGCCATCTCTTGGATTGACCAAGGCTTATAGCTAACAGATAGAACTGCGCGGGGATCTGACAGAGAGTAGCCCCGCGCCTGGGTTTAATCCTATCGACGTCTTGAAACTTCTCAATGAAAGGCGGGAGTTAGGATTTAGCGCCCAATTTCGTAAGGTTTCCAAGAACACGGAGTTCTCTACCGTTCCCCGCGCGCTGGCGAGATACGTCATGGCGTAGATCCGATGGTCCGGAATAGAGCGGCTCTTCCAGCCTAGTACCCTGGTGTCTTGGTGAGGTACCCCTAATTCCCGAAGGAGGCAATAAGACATAGCTTAAGCTCATTTTGTGGGCCTCTGTGGTTAAGCCGGTGGCCACGAACGGCTAAGAATAACACTAGTACATATGCTGGGAGCTCACTGGACTCTCTCAGACAGTAGAACCGGTGGCCAATGTGTTGAGTATAGCAAGTCCCGCCATACGGCAATTACGGCCCGCACTTTACGGTTGAATGGAACATCGGT"

reverse = ""

for nucleotide in DNA:
    if nucleotide == "T":
        reverse = "A" + reverse
    elif nucleotide == "A":
        reverse = "T" + reverse
    elif nucleotide == "G":
        reverse = "C" + reverse
    else:
        reverse = "G" + reverse

print(reverse)